### ISSUE TITLE
torrent-live

### ISSUE THREAD

**Issue by Ayms** [mafintosh/torrent-mount#12]
Just released here: https://github.com/Ayms/torrent-live

The main intent was the freerider behavior, see https://github.com/mafintosh/torrent-stream/issues/17

But then opening with the browser the file being downloaded just works to stream it inside the browser (and therefore it can be streamed to the TV real-time)

So, am I missing something or does torrent-mount do more?

**Comment by AliceDTRH** [comment]
I don't believe your software allows mounting torrents, does it?
Not everyone's primary use is watching video's.
Cool software though. Should be useful if I ever want to download something small from my main device.

**Comment by Ayms** [comment]
I don't remember exactly why I opened this ticket, what do you mean by "mounting torrents"

**Comment by AliceDTRH** [comment]
Don't worry about it.

**Comment by Ayms** [comment]
OK, closing then
