### ISSUE TITLE
Question: Is it possible to unmount the torrent?

### ISSUE THREAD

**Issue by herlon214** [mafintosh/torrent-mount#17]
If I already had a file, there is a way to unmount him?

Thanks in advance.

**Comment by mafintosh** [comment]
It should unmount when you 'ctrl-c' the process. Remember to quote the magnet argument if you are using bash as they usually contain `&` which makes the process run in the background otherwise

```
torrent-mount "magnet-link"
```

**Comment by herlon214** [comment]
Thanks for the response, but if I already had a file. There is a command to
create a magnetlink from a file?

2015-02-18 6:56 GMT-03:00 Mathias Buus <notifications@github.com>:

> It should unmount when you 'ctrl-c' the process. Remember to quote the
> magnet argument if you are using bash as they usually contain & which
> makes the process run in the background otherwise
>
> torrent-mount "magnet-link"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mafintosh/torrent-mount/issues/17#issuecomment-74838950>
> .
>



-- 
*Att, Herlon Aguiar*

**Comment by mafintosh** [comment]
If you already have a torrent file you should be able to just run `torrent-mount torrent-file.torrent` and then when you ctrl-c it should unmount

**Comment by herlon214** [comment]
Yeah, It solved my question.
Thanks.

2015-02-18 18:18 GMT-03:00 Mathias Buus <notifications@github.com>:

> If you already have a torrent file you should be able to just run torrent-mount
> torrent-file.torrent and then when you ctrl-c it should unmount
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mafintosh/torrent-mount/issues/17#issuecomment-74949827>
> .
>



-- 
*Att, Herlon Aguiar*
